PR1/PR1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings 
from django.conf.urls.static import static 
from login import views as login_views
from admin_ import views as admin_views
from home_ import views as home_views
from services import views as services_views
from beneficiaries import views as beneficiaries_views 
from activities import views as activities_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('home/', include('home_.urls')),
    path('login/', auth_views.LoginView.as_view(template_name = 'login/login.html'), name = 'login'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name = 'login/reset_password.html'), name = 'reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name = 'login/password_reset_sent.html'), name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = 'login/password_reset_form.html'), name = 'password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'login/password_reset_done.html'), name = 'password_reset_complete'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'login/logout.html'), name = 'logout'), 
    path('admin_/', include('admin_.urls')),
    path('activities/', include('activities.urls')),
    path('beneficiaries/', include('beneficiaries.urls')),
    path('services/', include('services.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

PR1/services/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('all_services/', views.Services, name='all_services'),
    path('new_Service/', views.CreateService, name='create_Service'),
    path('GetAllServices/', views.GetAllServices, name='GetAllServices'),
    path('GetServiceByID/<sid>', views.GetServiceByID, name='GetServiceByID'),
    path('UpdateService/<sid>', views.UpdateService, name='UpdateService'),
    path('DeleteService/<sid>', views.DeleteService, name='DeleteService')
]

PR1/admin/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    role = models.CharField(max_length = 50, choices = [('Admin','Admin'),('Team Leader','Team Leader'),('User','User')], default = 'User')
    
    def __str__(self):
        return f'{self.user.username} Profile'

PR1/services/models.py
from django.db import models
import datetime

class Service(models.Model):
    service_id = models.AutoField(primary_key = True)
    service_type = models.CharField(max_length = 50, choices = [
        ('GFA','GFA'),
        ('NFI','NFI'),
        ('WASH','WASH'),
        ('PSS','PSS'),
        ('LEG','LEG'),
        ('LH','LH'),
        ('CD','CD')
    ], null = False, blank = False)

    # Abbreviations: 
    # GFA: General Food Assistance.
    # NFI: Non-Food Items.
    # WASH: WAter, Sanitation and Health.
    # PSS: Psycho-Social Support.
    # LEG: LEGal services.
    # LH:  LiveliHoods
    # CD:  Capacity Development.
    
    service_description = models.TextField(null = True, blank = True)
    
    governorate =  models.CharField(max_length = 50, null = False, blank = False)
    district = models.CharField(max_length = 50, null = False, blank = False)
    sub_district = models.CharField(max_length = 50, null = False, blank = False)
    village_neighborhood = models.CharField(max_length = 50, null = False, blank = False)

    start_date = models.DateField(default = datetime.date.today, null = False, blank = False)
    end_date = models.DateField(null = False, blank = False)
    last_updated_by = models.EmailField(max_length=254, null = True, blank = True) 



    def __str__(self):
        return f'Service: {self.service_id} Type: {self.service_type}'

PR1/services/forms.py
from django import forms
from django.forms import ModelForm
from .models import Service 

class DateInput(forms.DateInput):
    input_type = 'date'

class ServiceForm(ModelForm):
    class Meta:
        model = Service
        fields = '__all__'
        widgets = {
            'start_date': DateInput(),
            'end_date': DateInput(),
            'last_updated_by': forms.HiddenInput()
        }

PR1/services/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from datetime import datetime
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .models import Service
from .serializers import ServiceSerializer
from .forms import ServiceForm
from django.http import FileResponse
import pandas as pd

# Web Views...

@login_required 
def Services(request):
    return render(request, 'services/services.html', {'form': ServiceForm()})


# API Views

@api_view(['GET'])
def GetAllServices(request):
    sr = Service.objects.all().order_by('service_id')
    serializer = ServiceSerializer(sr, many = True)
    return Response(serializer.data)


@api_view(['GET'])
def GetServiceByID(request, sid):
    try:
        sr = Service.objects.get(service_id = sid)
    except Service.DoesNotExist:
        return Response(status=404)
    
    serializer = ServiceSerializer(sr, many = False)
    return Response(serializer.data, status=201)


@api_view(['POST'])
def CreateService(request):
    serializer = ServiceSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=201)
    else:
        return Response(serializer.errors, status=400)


@api_view(['POST'])
def UpdateService(request, sid):
    try:
        sr = Service.objects.get(service_id = sid)
    except Service.DoesNotExist:
        return Response(status=404)

    serializer = ServiceSerializer(sr, data = request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=201)
    else:
        return Response(serializer.errors, status=400)


@api_view(['Get'])
def DeleteService(request, sid):
    try:
        sr = Service.objects.get(service_id = sid)
    except Service.DoesNotExist:
        return Response(status=404) 

    sr.delete()
    return redirect('all_services')

PR1/services/templates/services/services.html
{% extends "home_/base.html"%}
{% load crispy_forms_tags%}
{% block content %}
    <div class = "actionpage">
        <div class="action-header">

            <button class = 'btn-active' id = "create-service" style = "width: 200px;">Create New Service</button>
            <input type = "text" placeholder = "Search"id = 'srch' />
        </div>
        <table>
            <tr id="Grid">
                <th>Service ID:</th>
                <th>Service Type:</th>
                <th>Governorate:</th>
                <th>District:</th>
                <th>Sub-District:</th>
                <th>Village/Neighborhood:</th>
                <th>Start Date:</th>
                <th>End Date:</th>
                <th>Last updated by:</th>
                <th>Delete:</th>
            </tr>

        </table>
        <div class = 'messages-container'>
            {% if messages %}
                {% for message in messages %}
                    <p class = "{{message.tags}}">{{message}}</p>
                {% endfor %}
            {% endif %}
        </div>
        <div id="myModal" class="modal">
            <div class="modal-content"  style = "
                margin-top: 2%;
                width: 50%;
                height: 85%;
                ">
                <span class="close">&times;</span>
                <form method = 'POST' id = "ServiceCreationForm" style = "
                    margin-top: 2%;
                    margin-left: 2%;
                    width: 80%;
                    border-radius: 0px;
                    box-shadow: none;
                ">
                    {% csrf_token %}
                    <fieldset class = 'form-group'>
                        <legend class = 'legend-basic' id = "service-legend">Create New Service</legend>
                        {{form|crispy}}
                        <div class = 'form-group'>
                            <button class = 'btn-active' type = 'submit' id = 'submission'>Submit</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    <script>
$(document).ready(function(){
            $("#id_last_updated_by").val("{{user.email}}");
            var submission_method = 0;
            var uid;
            $('#srch').keyup(function(){
                search_table($(this).val());
            });

            function search_table(value){
                $('.table-row').each(function(){
        
                $(this).each(function(){
                    if($(this).text().toLocaleLowerCase().indexOf(value.toLocaleLowerCase()) >= 0){ $(this).show();}
                    else{$(this).hide();}
                    });
                });
            }

            $.getJSON('/services/GetAllServices/', function(data){
                for(var i=0; i < data.length; i++){                
                   $('#Grid').after("<tr class = ' table-row' id = '"+data[i].service_id+"''><td>"+data[i].service_id+"</td><td>"+data[i].service_type+"</td><td>"+data[i].governorate+"</td><td>"+data[i].district+"</td><td>"+data[i].sub_district+"</td><td>"+data[i].village_neighborhood+"</td><td>"+data[i].start_date.toString()+"</td><td>"+data[i].end_date.toString()+"<td>"+data[i].last_updated_by+"</td>"+"</td><td><a href='/services/DeleteService/"+data[i].service_id+"'>Delete</a></td></tr>");
                }

                $('.table-row').click(function(){
                    $('#myModal').show();
                    submission_method = 1;
                    var row_id = $(this).attr('id');
                    $('#service-legend').text('Edit Service');
                    $.getJSON("/services/GetServiceByID/" + row_id, function(data1){
                        $('#id_service_type').prepend("<option value = '"+data1.service_type+"' selected hidden>"+data1.service_type+"</option>");
                        $('#id_service_description').val(data1.service_description);
                        $('#id_governorate').val(data1.governorate);
                        $('#id_district').val(data1.district);
                        $('#id_sub_district').val( data1.sub_district);
                        $('#id_village_neighborhood').val(data1.village_neighborhood);
                        $('#id_start-date').val(data1.start_date);
                        $('#id_end_date').val(data1.end_date);
                        $('#id_role').prepend("<option value = '"+data1.role+"' selected hidden>"+data1.role+"</option>");
                        uid = data1.service_id;
                    });
                });
            });

            $('#create-service').click(function(){
                $('#myModal').show();
            });


          $('.close').click(function(){
                $('#myModal').hide();
                submission_method = 0;
                $('#id_service_type').prepend("<option value = '"+data1.service_type+"' selected hidden>"+data1.service_type+"</option>");
                $('#id_service_description').val('');
                $('#id_governorate').val('');
                $('#id_district').val('');
                $('#id_sub_district').val('');
                $('#id_village_neighborhood').val('');
                $('#id_start-date').val('');
                $('#id_end_date').val('');
            });

            $('#ServiceCreationForm').submit(function(event){
                event.preventDefault();
                if(submission_method == 0){
                    //create new service
                    $.ajax({
                        url: "/services/new_Service/",
                        type: "POST",
                        data: $(this).serialize(),
                        success: function(response){
                            alert('New service is successfully created... :)');
                            submission_method = 0;
                            window.location.reload();
                        },
                        error: function(xhr, status, error){
                            alert('Error while creating service... :(');
                            submission_method = 0;
                        }
                    });
                }
                else if(submission_method == 1){
                    //update current service
                    $.ajax({
                        url: "/services/UpdateService/"+ uid,
                        type: "POST",
                        data: $(this).serialize(),
                        success: function(response){
                            alert('Service is successfully updated... :)');
                            submission_method = 0;
                            window.location.reload();
                        },
                        error: function(xhr, status, error){
                            alert('Error while updating service... :(');
                            submission_method = 0;
                        }
                    });
                }
            });

        });
    </script>
    {% endblock %}