PR1/PR1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings 
from django.conf.urls.static import static 
from login import views as login_views
from admin_ import views as admin_views
from home_ import views as home_views
from services import views as services_views
from beneficiaries import views as beneficiaries_views 
from activities import views as activities_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('home/', include('home_.urls')),
    path('login/', auth_views.LoginView.as_view(template_name = 'login/login.html'), name = 'login'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name = 'login/reset_password.html'), name = 'reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name = 'login/password_reset_sent.html'), name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = 'login/password_reset_form.html'), name = 'password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'login/password_reset_done.html'), name = 'password_reset_complete'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'login/logout.html'), name = 'logout'), 
    path('admin_/', include('admin_.urls')),
    path('activities/', include('activities.urls')),
    path('beneficiaries/', include('beneficiaries.urls')),
    path('services/', include('services.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

PR1/activities/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('new_activity/', views.CreateActivity, name='create_activity'),
    path('GetAllActivities/', views.GetAllActivities, name='GetAllActivities'),
    path('GetActivityByID/<aid>', views.GetActivityByID, name='GetActivityByID'),
    path('UpdateActivity/<aid>', views.UpdateActivity, name='UpdateActivity'),
    path('DeleteActivity/<aid>', views.DeleteActivity, name='DeleteActivity'),
    path('register_activity/', views.RegisterActivity, name = 'register_activity'),
    path('history/<bid>', views.ViewHistory, name = 'history'),
    path('reports', views.Reports, name='reports'),
    path('infographic_report', views.InfogragphicReport, name = 'infographic-report')
]

PR1/activities/models.py
from django.db import models
from services.models import Service 
from beneficiaries.models import Beneficiary 

class Activity(models.Model):

    activity_id = models.AutoField(primary_key = True)
    service = models.ForeignKey(Service, on_delete = models.CASCADE)
    beneficiary = models.ForeignKey(Beneficiary, on_delete = models.CASCADE)
    comments = models.TextField(null = True, blank = True)
    last_updated_by = models.EmailField(max_length=254, null = True, blank = True)

PR1/activities/forms.py
from django import forms
from django.forms import DateInput
from django.forms import ModelForm
from .models import Activity


class ActivityForm(ModelForm):
    class Meta:
        model = Activity
        fields = '__all__'
        widgets = {
            'service': forms.TextInput(),
            'beneficiary': forms.TextInput(),
            'last_updated_by': forms.HiddenInput()
        }




class EventForm(forms.Form):
    start_date = forms.DateField(widget=DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(widget=DateInput(attrs={'type': 'date'}))
    report_type = forms.ChoiceField(choices=[('4Ws', '4Ws'), ('Infographic', 'Infographic')]) 

PR1/activities/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from datetime import datetime
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .models import Activity
from .serializers import ActivitySerializer
from .forms import ActivityForm, EventForm
from django.http import FileResponse
from beneficiaries.models import Beneficiary
import pandas as pd
import requests
from io import BytesIO
from datetime import datetime


def GetFourWsData(start_date, end_date):
    response = requests.get("http://127.0.0.1:8000/activities/GetAllActivities/")
    response.raise_for_status()
    if response.headers['Content-Type'] == 'application/json':
        data = response.json()
        df = pd.json_normalize(data)
        df['service.start_date'] = pd.to_datetime(df['service.start_date']).dt.date
        df['service.end_date'] = pd.to_datetime(df['service.end_date']).dt.date

        df = df[df['service.start_date'] >= start_date]
        df = df[df['service.end_date'] <= end_date]

        grouped_df = df.groupby(['service.service_type','service.start_date', 'service.end_date','service.governorate', 'service.district', 'service.sub_district','service.village_neighborhood']).agg(
                            Total_individuals = ('beneficiary.householod_size', 'sum'),
                            Males=('beneficiary.sex', pd.NamedAgg(column='beneficiary.sex', aggfunc=lambda x: len(x[x == 'Male']))),
                            Females=('beneficiary.sex', pd.NamedAgg(column='beneficiary.sex', aggfunc=lambda x: len(x[x == 'Female']))),
                            Disabilities=('beneficiary.disability_in_household', pd.NamedAgg(column='beneficiary.disability_in_household', aggfunc=lambda x: len(x[x == 'Yes']))),
                            Infants=('beneficiary.infants_in_household', pd.NamedAgg(column='beneficiary.infants_in_household', aggfunc=lambda x: len(x[x == 'Yes']))),
                            Elders=('beneficiary.elders_in_household', pd.NamedAgg(column='beneficiary.elders_in_household', aggfunc=lambda x: len(x[x == 'Yes']))),
                            Residents = ('beneficiary.displacement_status', pd.NamedAgg(column = 'beneficiary.displacement_staus', aggfunc = lambda x: len(x[x=='Resident']))),
                            Refugees = ('beneficiary.displacement_status', pd.NamedAgg(column = 'beneficiary.displacement_staus', aggfunc = lambda x: len(x[x=='Refugee']))),
                            Returnees = ('beneficiary.displacement_status', pd.NamedAgg(column = 'beneficiary.displacement_staus', aggfunc = lambda x: len(x[x=='Returnee']))),
                            IDPs = ('beneficiary.displacement_status', pd.NamedAgg(column = 'beneficiary.displacement_staus', aggfunc = lambda x: len(x[x=='IDP']))),
                    )

    return grouped_df


def GetFlashReport(start_date, end_date):
    response = requests.get("http://127.0.0.1:8000/activities/GetAllActivities/")
    response.raise_for_status()
    if response.headers['Content-Type'] == 'application/json':
        data = response.json()
        df = pd.json_normalize(data)
        df['service.start_date'] = pd.to_datetime(df['service.start_date']).dt.date
        df['service.end_date'] = pd.to_datetime(df['service.end_date']).dt.date

        df = df[df['service.start_date'] >= start_date]
        df = df[df['service.end_date'] <= end_date]

    bens = df[['beneficiary.beneficiary_id', 'beneficiary.first_name',
       'beneficiary.middle_name', 'beneficiary.last_name',
       'beneficiary.date_of_birth', 'beneficiary.place_of_birth',
       'beneficiary.sex', 'beneficiary.national_identifier_type',
       'beneficiary.national_identifier_number', 'beneficiary.contact_number',
       'beneficiary.current_address', 'beneficiary.displacement_status',
       'beneficiary.beneficiary_pic', 'beneficiary.householod_size',
       'beneficiary.disability_in_household', 'beneficiary.disability_type',
       'beneficiary.elders_in_household', 'beneficiary.infants_in_household',
       'beneficiary.occupation', 'beneficiary.education']].drop_duplicates()

    total_reach = bens['beneficiary.householod_size'].sum()
    household = bens.shape[0]
    males = len(bens[bens['beneficiary.sex'] == 'Male'])
    females = len(bens[bens['beneficiary.sex'] == 'Female'])
    disabled = len(bens[bens['beneficiary.disability_in_household'] == 'Yes'])
    residents = len(bens[bens['beneficiary.displacement_status'] == 'Resident'])
    returnees = len(bens[bens['beneficiary.displacement_status'] == 'Returnee'])
    refugees = len(bens[bens['beneficiary.displacement_status'] == 'Refugee'])
    idps = len(bens[bens['beneficiary.displacement_status'] == 'IDP'])

    services  = df[['service.service_type','beneficiary.householod_size']]

    nfi = services[services['service.service_type'] == 'NFI']['beneficiary.householod_size'].sum()
    gfa = services[services['service.service_type'] == 'GFA']['beneficiary.householod_size'].sum()
    wash = services[services['service.service_type'] == 'WASH']['beneficiary.householod_size'].sum()
    pss = services[services['service.service_type'] == 'PSS']['beneficiary.householod_size'].sum()
    lh = services[services['service.service_type'] == 'LH']['beneficiary.householod_size'].sum()
    cd_ = services[services['service.service_type'] == 'CD']['beneficiary.householod_size'].sum()
    leg = services[services['service.service_type'] == 'LEG']['beneficiary.householod_size'].sum()

    context = {
        'total_reach': total_reach,
        'household':household,
        'males':males,
        'females':females,
        'disabled':disabled,
        'residents':residents,
        'returnees':returnees,
        'refugees':refugees,
        'idps':idps,
        'nfi':nfi,
        'gfa':gfa,
        'wash':wash,
        'pss':pss,
        'lh':lh,
        'cd_':cd_,
        'leg':leg,
        'start_date': start_date,
        'end_date': end_date
    }

    return context


@login_required
def RegisterActivity(request):
    return render(request, 'activities/register_activity.html', {'form': ActivityForm})

@login_required
def ViewHistory(request, bid):
    bn = Beneficiary.objects.get(beneficiary_id = bid)
    ac = Activity.objects.filter(beneficiary = bn)
    services = set(activity.service for activity in ac)
    return render(request, 'activities/history.html', {'ben': bn, 'ser': services})

@login_required
def Reports(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            report_type = form.cleaned_data['report_type']
            if report_type == '4Ws':
                df = GetFourWsData(start_date, end_date)
                buffer = BytesIO()
                df.to_excel(buffer, index=True)
                filename = 'four_ws_data.xlsx'
                response = HttpResponse(
                    buffer.getvalue(), 
                    content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                )
                response['Content-Disposition'] = f'attachment; filename="{filename}"'
                return response  
            elif report_type == 'Infographic':
                context = GetFlashReport(start_date, end_date)
                return render(request, 'activities/infographic_report.html', context = context)

            
    else:
        form = EventForm()
    return render(request, 'activities/reports.html', {'form': form})


@login_required
def InfogragphicReport(request):
    return render(request, 'activities/infographic_report.html')




# API Views


@api_view(['GET'])
def GetAllActivities(request):
    ac = Activity.objects.all().order_by('activity_id')
    serializer = ActivitySerializer(ac, many = True)
    return Response(serializer.data)


@api_view(['GET'])
def GetActivityByID(request, aid):
    try:
        ac = Activity.objects.get(activity_id = aid)
    except Activity.DoesNotExist:
        return Response(status=404)
    
    serializer = ActivitySerializer(ac, many = False)
    return Response(serializer.data, status=201)


@api_view(['POST'])
def CreateActivity(request):
    serializer = ActivitySerializer(data = request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=201)
    else:
        return Response(serializer.errors, status=400)


@api_view(['POST'])
def UpdateActivity(request, aid):
    try:
        ac = Activity.objects.get(activity_id = aid)
    except Activity.DoesNotExist:
        return Response(status=404)

    serializer = ActivitySerializer(ac, data = request.data)
    if serializer.is_valid():
        seralizer.save()
        return Response(serializer.data, status=201)
    else:
        return Response(serializer.errors, status=400)


@api_view(['GET'])
def DeleteActivity(request, aid):
    try:
        ac = Activity.objects.get(activity_id = aid)
    except Activity.DoesNotExist:
        return Response(status=404) 

    ac.delete()
    return redirect('reports')

PR1/activities/templates/activities/history.html
{% extends "home_/base.html"%}
{% load crispy_forms_tags%}
{% block content %}
{% load static %}
<div class = "ben_section">
    <img src="{{ben.beneficiary_pic.url}}"  class = 'ben-pic'>
    <h5  class = 'bid' id = "{{ben.beneficiary_id}}">ID: {{ben.beneficiary_id}}</h5>
    <h3 id = >{{ ben.first_name }} {{ben.middle_name}} {{ben.last_name}}</h3>
    <table class = 'ben-info'>
        <tr>
            <td>Date of Birth:</td>
            <td>{{ben.date_of_birth}}</td>
            <td>Place of Birth:</td>
            <td>{{ben.place_of_birth}}</td>
        </tr>
        <tr>
            <td>Sex:</td>
            <td>{{ben.sex}}</td>
            <td>Household Size:</td>
            <td>{{ben.householod_size}}</td>
        </tr>
        <tr>
            <td>Displacement Status:</td>
            <td>{{ben.displacement_status}}</td>
            <td>Contact:</td>
            <td>{{ben.contact_number}}</td>
        </tr>
        <tr>
            <td>Current Address:</td>
            <td>{{ben.current_address}}</td>
        </tr>
        <tr>
            <td>National Identifier:</td>
            <td>{{ben.national_identifier_type}}</td>
            <td>National Identifier Number:</td>
            <td>{{ben.national_identifier_number}}</td>
        </tr>
    </table>
    <a href = "{% url 'beneficiaries_register'%}"><button class = 'btn-clear'>Back to Register</button></a>
    <div class = "services">
        <table>
            <tr>
                <th>Service ID:</th>
                <th>Service Type:</th>
                <th>Governorate:</th>
                <th>District:</th>
                <th>Sub-District:</th>
                <th>Village/Neighborhood:</th>
                <th>Start Date:</th>
                <th>End Date:</th>
            </tr>
            {% for s in ser %}
                <tr>
                    <td>{{s.service_id}}</td>
                    <td>{{s.service_type}}</td>
                    <td>{{s.governorate}}</td>
                    <td>{{s.district}}</td>
                    <td>{{s.sub_district}}</td>
                    <td>{{s.village_neighborhood}}</td>
                    <td>{{s.start_date}}</td>
                    <td>{{s.end_date}}</td>
                </tr>
            {% endfor %}

        </table>
    </div>
    </div>

{%endblock%}

PR1/activities/templates/activities/infographic_report.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.7.1.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/davidshimjs/qrcodejs/qrcode.min.js"></script>
        <script type = "text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.2/jspdf.min.js"></script>
        <script type = "text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.1.4/html2canvas.min.js"></script>
        <link rel="icon" type="image/x-icon" href="{% static 'login/images/sarc-icon.jpg'%}">
        <title>B.R.A.V.e.S</title>
      </head>
      <body id = 'page'>
        <div class = 'top-ribbon'>
            <img class = 'robbin-icon' src = "{% static 'login/images/sarc-icon.jpg'%}" />
            <h1 class = 'ribbon-title'>Syrian Arab Red Crescent Infographic Report</h1>
            <h2 class = 'ribbon-dates'>From: {{start_date}} - to: {{end_date}}</h2>
        </div>
        <div class = 'content'>
            <table class = 'infographic-content'>
                <tr>
                    <td>
                        <div>
                            <img class = 'service-icon' src="{% static 'home_/images/population.jpg'%}" style = "height: 100px; width: 100px;"/>
                            <h1 class = 'service-title'>Total Reach</h1>
                        </div>
                        <div class = 'section'>
                            <h1 class = 'figure'>{{total_reach}}</h1>
                            <p class = 'caption'> Indiduals have benefited from all Syrian Arab Red Crescent services during the reporting period accross the country.</p>
                        </div>
                    </td>
                    <td>
                        <div>
                            <img class = 'service-icon' src="{% static 'home_/images/household.png'%}" style = "height: 100px; width: 100px;"/>
                            <h1 class = 'service-title'>Households</h1>
                        </div>
                        <div class = 'section'>
                            <h1 class = 'figure'>{{household}}</h1>
                            <p class = 'caption'> Households have benefited from all Syrian Arab Red Crescent services during the reporting period accross the country.</p>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td style = "width: 33%;">
                        <div>
                            <img class = 'service-icon' src="{% static 'home_/images/gender_breakdown.jpg'%}" style = "height: 100px; width: 100px;"/>
                            <h1 class = 'service-title'>Gender Breakdown</h1>
                        </div>
                        <div class = 'section'>
                            <h1 class = 'figure' style = 'color: white;'>_</h1>
                            <p class = 'caption'> The total of <span style="font-weight: bold;">{{males}} Male</span> and <span style = "font-weight: bold;">{{females}} Female</span> headed households have benefited from Syrian Arab Red Crescent services accross the country during the reporting period.</p>
                        </div>
                    </td>
                    <td style = "width: 33%;">
                        <div>
                            <img class = 'service-icon' src="{% static 'home_/images/disability.png'%}" style = "height: 100px; width: 100px;"/>
                            <h1 class = 'service-title'>Disabilities</h1>
                        </div>
                        <div class = 'section'>
                            <h1 class = 'figure'>{{disabled}}</h1>
                            <p class = 'caption'> Households with disabled persons have benefited from special Sryian Arab Red Crescent services accross the country during the reporting period.</p>
                        </div>
                    </td>
                    <td style = "width: 33%;">
                        <div>
                            <img class = 'service-icon' src="{% static 'home_/images/displacement.webp'%}" style = "height: 100px; width: 100px;"/>
                            <h1 class = 'service-title'>Displacement</h1>
                        </div>
                        <div class = 'section'>
                            <h1 class = 'figure' style = 'color: white;'>_</h1>
                            <p class = 'caption'> The total of <span style="font-weight: bold;">{{residents}} Resident</span>, <span style = "font-weight: bold;">{{returnees}} Returnee</span>, </p>
                            <p class = 'caption'><span style = "font-weight: bold;">{{idps}} IDP</span> and <span style = "font-weight: bold;">{{refugees}} Refugee</span> households have benefited from Syrian Arab Red Crescent services accross the country during the reporting period.</p>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
        <div class = 'content'>
            <table class = 'infographic-content'>
                <tr>
                    <td>
                        <div>
                            <img class = 'service-icon' src="{% static 'home_/images/NFI.png'%}">
                            <h1 class = 'service-title'>Non Food Items (NFI)</h1>
                        </div>
                        <div class = 'section'>
                            <h1 class = 'figure'>{{nfi}}</h1>
                            <p class = 'caption'> individuals have benefited from <span style = "font-weight: bold;">NFI</span> services during the reporting period</p>
                        </div>
                    <td>
                        <div>
                            <img class = 'service-icon' src="{% static 'home_/images/GFA.png'%}">
                            <h1 class = 'service-title'>General Food Assistance (GFA)</h1>
                        </div>
                        <div class = 'section'>
                            <h1 class = 'figure'>{{gfa}}</h1>
                            <p class = 'caption'> individuals have benefited from <span style = "font-weight: bold;">GFA</span>  services during the reporting period</p>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div>
                            <img class = 'service-icon' src="{% static 'home_/images/WASH.png'%}">
                            <h1 class = 'service-title'>Water, Health and Sanitation (WASH)</h1>
                        </div>
                        <div class = 'section'>
                            <h1 class = 'figure'>{{wash}}</h1>
                            <p class = 'caption'> individuals have benefited from <span style = "font-weight: bold;">WASH</span>  services during the reporting period</p>
                        </div>
                    </td>
                    <td>
                        <div>
                            <img class = 'service-icon' src="{% static 'home_/images/PSS.png'%}">
                            <h1 class = 'service-title'>Psycho-Social Support (PSS)</h1>
                        </div>
                        <div class = 'section'>
                            <h1 class = 'figure'>{{pss}}</h1>
                            <p class = 'caption'> individuals have benefited from <span style = "font-weight: bold;">PSS</span>  services during the reporting period</p>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div>
                            <img class = 'service-icon' src="{% static 'home_/images/LH.png'%}">
                            <h1 class = 'service-title'>Livelihoods (LH)</h1>
                        </div>
                        <div class = 'section'>
                            <h1 class = 'figure'>{{lh}}</h1>
                            <p class = 'caption'> individuals have benefited from <span style = "font-weight: bold;">LH</span>  services during the reporting period</p>
                        </div>
                    </td>
                    <td>
                        <div>
                            <img class = 'service-icon' src="{% static 'home_/images/CD.png'%}">
                            <h1 class = 'service-title'>Capacity Development (CD)</h1>
                        </div>
                        <div class = 'section'>
                            <h1 class = 'figure'>{{cd_}}</h1>
                            <p class = 'caption'> individuals have benefited from <span style = "font-weight: bold;">CD</span>  services during the reporting period</p>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div>
                            <img class = 'service-icon' src="{% static 'home_/images/LEG.png'%}">
                            <h1 class = 'service-title'>Legal Services (LEG)</h1>
                        </div>
                        <div>
                            <h1 class = 'figure'>{{leg}}</h1>
                            <p class = 'caption'> individuals have benefited from <span style = "font-weight: bold;">LEG</span>  services during the reporting period</p>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
        <div class = 'bottom-ribbon'></div>
      </body>
      <style>
        body{
            margin: 0px;
            padding: 0px;
            background-color: rgb(231, 231, 231);
        }
        .top-ribbon{
            background-color: rgb(200, 0, 0);
            width: 100%;
            height: 150px;
            padding: 10px;
        }

        .robbin-icon{
            width: 150px;
            height: 150px;
            border-radius: 75px;
            float: left;
            margin-right: 50px;
        }


        .ribbon-title{
            padding-top: 10px;
            font-family: "Arial Black", Gadget, sans-serif;
            font-weight: bolder;
            color: white;
        }

        .ribbon-dates{
            font-family: "Arial Black", Gadget, sans-serif;
            font-weight: bolder;
            color: white;
        }

        .content{
            padding-top: 2%;
            padding-left: 5%;
        }

        .infographic-content{
            background-color: white;
            width: 95%;
            border-collapse: collapse;
            margin-bottom: 5px;
        }

        td{
            border-bottom:5pt solid rgb(2, 23, 83);
            border-right: 10pt solid white;
            border-left: 10pt solid white;
        }

        .service-icon{
            margin-top: 20px;
            margin-left: 20px;
            float: left;
            margin-right: 10px;
        }

        .service-title{
            font-family: "Arial Black", Gadget, sans-serif;
            font-weight: bolder;
            color: rgb(2, 23, 83);
            padding-top: 40px;
            padding-left: 10px;
        }

        .section{
            float: left;
        }

        .figure{
            font-family: "Arial Black", Gadget, sans-serif;
            font-weight: bolder;
            color: black;
        }

        .caption{
            font-size: 22px;
        }

        .bottom-ribbon{
            margin-top: 75px;
            width: 100%;
            height: 50px;
            background-color: rgb(200,0,0);
        }
      </style>
      <script>
        $(document).ready(function(){
           
            const div = document.getElementById('page');
 
            html2canvas(div).then(canvas => {
            const imgData = canvas.toDataURL('image/png');

            const doc = new jsPDF();

            doc.addImage(imgData, 'JPEG',  0,25, 215, 200);
            doc.save('SARC Flash Report.pdf');
            });
        });
      </script>
</html>

PR1/activities/templates/activities/register_activity.html
{% extends "home_/base.html"%}
{% load crispy_forms_tags%}
{% block content %}
{% load static %}

<form method = 'POST' id = "ActivityRegisterForm" style = "
                    margin-top: 5%;
                    margin-left: 2%;
                    padding-top: 30px;
                    width: 50%;
                    height: 100%;
                    border-radius: 0px;
                    box-shadow: none;
                " enctype="multipart/form-data">
                    {% csrf_token %}
    <fieldset class = 'form-group'>
        <legend class = 'legend-basic' id = "service-legend">Service Delivery</legend>
            {{form|crispy}}
        <div class = 'form-group'>
            <button class = 'btn-active' type = 'submit' id = 'submission'>Submit</button>
            <button class = 'btn-clear' id = 'form-clear'>Clear</button>
        </div>
    </fieldset>
</form>
<script>
    $(document).ready(function(){
        $("#id_last_updated_by").val("{{user.email}}");
        $('#ActivityRegisterForm').submit(function(event){
            event.preventDefault();
            $.getJSON("/services/GetServiceByID/"+$('#id_service').val(), function(data1){
                $.getJSON("/beneficiaries/GetBeneficiaryByID/"+$('#id_beneficiary').val(), function(data2){
                    printout(data1, data2);
                });
            });

  

        });

        $('#form-clear').click(function(event){
            event.preventDefault();
            window.location.reload();
        });

        var csrftoken = '{{ csrf_token }}'

        function printout(data1, data2){
            var activity = {
                "service":{
                    "service_id": data1.service_id,
                    "service_type": data1.service_type,
                    "governorate": data1.governorate,
                    "district": data1.district,
                    "sub_district": data1.sub_district,
                    "village_neighborhood": data1.village_neighborhood,
                    "start_date": data1.start_date,
                    "end_date": data1.end_date
                },
                "beneficiary":{
                    "beneficiary_id": data2.beneficiary_id,
                    "first_name": data2.first_name,
                    "middle_name": data2.middle_name,
                    "last_name": data2.last_name,
                    "date_of_birth": data2.date_of_birth,
                    "place_of_birth": data2.place_of_birth,
                    "sex": data2.sex,
                    "national_identifier_type": data2.national_identifier_type,
                    "national_identifier_number": data2.national_identifier_number,
                    "contact_number": data2.contact_number,
                    "current_address": data2.current_address,
                    "displacement_status": data2.displacement_status,
                    "householod_size": data2.householod_size,
                    "disability_in_household": data2.disability_in_household,
                    "disability_type": data2.disability_type,
                    "elders_in_household": data2.elders_in_household,
                    "infants_in_household": data2.infants_in_household,
                    "occupation": data2.occupation,
                    "education": data2.education
                }
            }
            $.ajax({
                        url: "/activities/new_activity/",
                        type: "POST",
                        data: JSON.stringify(activity),
                        contentType: "application/json", 
                        headers: {
                                'X-CSRFToken': csrftoken 
                        },
                        success: function(response){
                            alert('New Record is successfully created... :)');
                            submission_method = 0;
                            window.location.reload();
                        },
                        error: function(xhr, status, error){
                            alert('Error while creating record... :(');
                            submission_method = 0;
                        }
                    });
        }
    });
</script>

{%endblock%}