PR1/PR1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings 
from django.conf.urls.static import static 
from login import views as login_views
from admin_ import views as admin_views
from home_ import views as home_views
from services import views as services_views
from beneficiaries import views as beneficiaries_views 
from activities import views as activities_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('home/', include('home_.urls')),
    path('login/', auth_views.LoginView.as_view(template_name = 'login/login.html'), name = 'login'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name = 'login/reset_password.html'), name = 'reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name = 'login/password_reset_sent.html'), name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = 'login/password_reset_form.html'), name = 'password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'login/password_reset_done.html'), name = 'password_reset_complete'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'login/logout.html'), name = 'logout'), 
    path('admin_/', include('admin_.urls')),
    path('activities/', include('activities.urls')),
    path('beneficiaries/', include('beneficiaries.urls')),
    path('services/', include('services.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

PR1/beneficiaries/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('beneficiaries_register/', views.Beneficiaries, name='beneficiaries_register'),
    path('new_Beneficiary/', views.CreateBeneficiary, name='create_Beneficiary'),
    path('GetAllBeneficiaries/', views.GetAllBeneficiaries, name='GetAllBeneficiaries'),
    path('GetBeneficiaryByID/<bid>', views.GetBeneficiaryByID, name='GetBeneficiaryByID'),
    path('UpdateBeneficiary/<bid>', views.UpdateBeneficiary, name='UpdateBeneficiary'),
    path('DeleteBeneficiary/<bid>', views.DeleteBeneficiary, name='DeleteBeneficiary'),
    path('PrintID/<bid>', views.PrintID, name = 'print-id')
]

PR1/beneficiaries/models.py
from django.db import models

class Beneficiary(models.Model):
    beneficiary_id = models.AutoField(primary_key = True)
    first_name = models.CharField(max_length = 50, null = False, blank = False)
    middle_name = models.CharField(max_length = 50, null = False, blank = False)
    last_name = models.CharField(max_length = 50, null = False, blank = False)
    date_of_birth = models.DateField(null = False, blank = False)
    place_of_birth = models.CharField(max_length = 100, null = False, blank = False)
    sex = models.CharField(max_length = 10, choices = [('Male','Male'), ('Female','Female')])
    national_identifier_type = models.CharField(max_length = 20, choices = [
        ('National ID','National ID'),
        ('Family Booklet','Family Booklet'),
        ('Other','Other'),
        ('None','None')
    ], default = 'None', null = False, blank = False)

    national_identifier_number = models.CharField(max_length = 100)

    contact_number = models.CharField(max_length=10, null = False, blank = False)
    current_address = models.CharField(max_length=100, null = False, blank = False)
    displacement_status=models.CharField(max_length = 15, choices = [
        ('IDP', 'IDP'),
        ('Refugee','Refugee'),
        ('Returnee','Returnee'),
        ('Resident', 'Resident')
    ], null = False, blank = False)

    beneficiary_pic = models.ImageField(null = True, blank = True, upload_to = "images/")

    householod_size = models.IntegerField(default = 1, null = False, blank = False)
    disability_in_household = models.CharField(max_length = 3, choices = [('Yes','Yes'),('No','No')], default = 'No', null = False, blank = False)
    disability_type = models.CharField(max_length = 25, choices = [
        ('None','None'),
        ('Mobility','Mobility'),
        ('Vision','Vision'),
        ('Hearing','Hearing'),
        ('Mental','Mental')
    ], default = 'None', null = False, blank = False)
    elders_in_household = models.CharField(max_length = 5, choices = [('Yes','Yes'),('No','No')], default = 'No', null = False, blank = False)
    infants_in_household = models.CharField(max_length = 5, choices = [('Yes','Yes'),('No','No')], default = 'No', null = False, blank = False)

    occupation = models.CharField(max_length=100, null=False, blank=False, default = 'None')
    education = models.CharField(max_length=100, choices = [
        ('None','None'),
        ('Primary','Primary'),
        ('Intermediate','Intermediate'),
        ('Secondary','Secondary'),
        ('Collage-University','Collage-University'),
        ('Post Grad','Post Grad')
    ], default = 'None', null = False, blank = False)

    last_updated_by = models.EmailField(max_length=254, null = True, blank = True)


    def __str__(self):
        return f'Beneficiary ID: {self.beneficiary_id} Name: {str(self.last_name).upper()}, {self.first_name} {self.middle_name}, Sex: {self.sex}, Status: {self.displacement_status}'
        

PR1/beneficiaries/forms.py
from django import forms
from django.forms import ModelForm
from .models import Beneficiary

class DateInput(forms.DateInput):
    input_type = 'date'

class BeneficiaryForm(ModelForm):
    class Meta:
        model = Beneficiary
        fields = '__all__'
        widgets = {
            'date_of_birth': DateInput(),
            'last_updated_by': forms.HiddenInput()
        }

PR1/beneficiaries/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from datetime import datetime
from rest_framework.decorators import api_view, parser_classes
from rest_framework.response import Response
from .models import Beneficiary
from .serializers import BeneficiarySerializer
from .forms import BeneficiaryForm
from django.http import FileResponse
from rest_framework.parsers import MultiPartParser, FormParser
import pandas as pd
import pyqrcode
from PIL import Image, ImageDraw, ImageFont
from django.conf import settings
import os
from xhtml2pdf import pisa
from django.http import HttpResponse


@login_required
def Beneficiaries(request):
    return render(request, 'beneficiaries/beneficiaries_register.html',{'form': BeneficiaryForm})

@login_required
def PrintID(request, bid):
    try:
        bn = Beneficiary.objects.get(beneficiary_id = bid)
    except Beneficiary.DoesNotExist:
        return False 
    return render(request, 'beneficiaries/beneficiary_id.html', {'ben': bn})



# API Views


@api_view(['GET'])
def GetAllBeneficiaries(request):
    bn = Beneficiary.objects.all().order_by('beneficiary_id')
    serializer = BeneficiarySerializer(bn, many = True)
    return Response(serializer.data)


@api_view(['GET'])
def GetBeneficiaryByID(request, bid):
    try:
        bn = Beneficiary.objects.get(beneficiary_id = bid)
    except Beneficiary.DoesNotExist:
        return Response(status=404)
    
    serializer = BeneficiarySerializer(bn, many = False)
    return Response(serializer.data, status=201)


@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser])
def CreateBeneficiary(request, format = None):
    data_ = request.data.copy() 
    ben_name = f"{data_['first_name']}_{data_['middle_name']}_{data_['last_name']}" 
    serializer = BeneficiarySerializer(data = data_)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=201)
    else:
        return Response(serializer.errors, status=400)


@api_view(['POST'])
def UpdateBeneficiary(request, bid):
    try:
        bn = Beneficiary.objects.get(beneficiary_id = bid)
    except Beneficiary.DoesNotExist:
        return Response(status=404)

    serializer = BeneficiarySerializer(bn, data = request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=201)
    else:
        return Response(serializer.errors, status=400)


@api_view(['GET'])
def DeleteBeneficiary(request, bid):
    try:
        bn = Beneficiary.objects.get(beneficiary_id = bid)
    except Beneficiary.DoesNotExist:
        return Response(status=404) 

    bn.delete()
    return redirect('beneficiaries_register')

PR1/beneficiaries/templates/beneficiaries/beneficiaries_register.html
{% extends "home_/base.html"%}
{% load crispy_forms_tags%}
{% block content %}
{% load static %}
    <div class = "actionpage">
        <div class="action-header">
            <input type = "text" placeholder = "Search"id = 'srch' />
        </div>
        <div class = "action-header" id="beneficiaries-table" style="display: none;">
            <button class = 'btn-clear' id = "clear-search" style = "width: 200px;">Clear Search</button>
            <table>
                <tr id="Grid">
                    <th>Beneficiary ID:</th>
                    <th>First Name:</th>
                    <th>Middle Name:</th>
                    <th>Last Name:</th>
                    <th>Date of Birth:</th>
                    <th>Place of Birth:</th>
                    <th>Sex:</th>
                    <th>National Identifier:</th>
                    <th>National Identifier Number:</th>
                    <th>Last updated by:</th>
                    <th>Delete:</th>
                    <th>Print ID:</th>
                    <th>History:</th>
                </tr>
            </table>
        </div>
        
        <div class = 'messages-container'>
            {% if messages %}
                {% for message in messages %}
                    <p class = "{{message.tags}}">{{message}}</p>
                {% endfor %}
            {% endif %}
        </div>
        <form method = 'POST' id = "BeneficiaryCreationForm" style = "
                    margin-top: 2%;
                    margin-left: 2%;
                    padding-top: 30px;
                    width: 80%;
                    height: 100%;
                    border-radius: 0px;
                    box-shadow: none;
                " enctype="multipart/form-data">
                    {% csrf_token %}
            <fieldset class = 'form-group'>
                <legend class = 'legend-basic' id = "service-legend">Create New Beneficiary</legend>
                <img src = "{% static 'home_/images/default_pic.jpg'%}" class = 'ben-pic'/>
                    {{form|crispy}}
                <div class = 'form-group'>
                    <button class = 'btn-active' type = 'submit' id = 'submission'>Submit</button>
                    <button class = 'btn-clear' id = 'form-clear'>Clear</button>
                </div>
            </fieldset>
        </form>
    </div>
    <script>
$(document).ready(function(){
            $("#id_last_updated_by").val("{{user.email}}");
            var submission_method = 0;
            var uid;
            $('#srch').keyup(function(){
                search_table($(this).val());
            });

            function search_table(value){
                $('.table-row').each(function(){
        
                $(this).each(function(){
                    if($(this).text().toLocaleLowerCase().indexOf(value.toLocaleLowerCase()) == 0){
                        $('#beneficiaries-table').hide();
                    }
                    else if($(this).text().toLocaleLowerCase().indexOf(value.toLocaleLowerCase()) >= 0){ 
                        $('#beneficiaries-table').show();
                        $(this).show();
                    }
                    else{
                        $(this).hide();
                    }
                    });
                });
            }

            $("#clear-search").click(function(){
                $('#beneficiaries-table').hide();
            });

            $.getJSON('/beneficiaries/GetAllBeneficiaries/', function(data){
                for(var i=0; i < data.length; i++){                
                   $('#Grid').after("<tr class = 'table-row' id = '"+data[i].beneficiary_id+"''><td>"+data[i].beneficiary_id+"</td><td>"+data[i].first_name+"</td><td>"+data[i].middle_name+"</td><td>"+data[i].last_name+"</td><td>"+data[i].date_of_birth.toString()+"</td><td>"+data[i].place_of_birth+"</td><td>"+data[i].sex+"</td><td>"+data[i].national_identifier_type+"</td><td>"+data[i].national_identifier_number+"</td>"+"<td>"+data[i].last_updated_by+"</td>"+"<td><a href='/beneficiaries/DeleteBeneficiary/"+data[i].beneficiary_id+"'>Delete</a></td><td><a href = '/beneficiaries/PrintID/"+data[i].beneficiary_id+"'>Print ID</a></td><td><a href = '/activities/history/"+data[i].beneficiary_id+"'>View History</a></td></tr>");
                }

                $('.table-row').click(function(){
                    $('#myModal').show();
                    submission_method = 1;
                    var row_id = $(this).attr('id');
                    $('#service-legend').text('Edit Beneficiary');
                    $.getJSON("/beneficiaries/GetBeneficiaryByID/" + row_id, function(data1){

                        $('.ben-pic').attr('src',data1.beneficiary_pic);
                        $('#id_first_name').val(data1.first_name);
                        $('#id_middle_name').val(data1.middle_name);
                        $('#id_last_name').val(data1.last_name);
                        $('#id_date_of_birth').val(data1.date_of_birth);
                        $('#id_place_of_birth').val(data1.place_of_birth);
                        $('#id_sex').val(data1.sex);
                        $('#id_national_identifier_type').prepend("<option value = '"+data1.national_identifier_type+"' selected hidden>"+data1.national_identifier_type+"</option>");
                        $('#id_national_identifier_number').val(data1.national_identifier_number);
                        $('#id_contact_number').val(data1.contact_number);
                        $('#id_current_address').val(data1.current_address);
                        $('#id_displacement_status').prepend("<option value = '"+data1.displacement_status+"' selected hidden>"+data1.dispacement_status+"</option>");
                        $('#id_beneficiary_pic').attr('value', data1.beneficiary_pic);
                        $('#id_household_size').val(data1.household_size);
                        $('#id_disability_in_household').prepend("<option value = '"+data1.disability_in_household+"' selected hidden>"+data1.disability_in_household+"</option>");
                        $('#id_disability_type').prepend("<option value = '"+data1.disability_type+"' selected hidden>"+data1.disability_type+"</option>");
                        $('#id_elders_in_household').prepend("<option value = '"+data1.elders_in_household+"' selected hidden>"+data1.elders_in_household+"</option>");
                        $('#id_infants_in_household').prepend("<option value = '"+data1.infants_in_household+"' selected hidden>"+data1.infants_in_household+"</option>");
                        $('#id_occupation').val(data1.occupation);
                        $('#id_education').prepend("<option value = '"+data1.education+"' selected hidden>"+data1.education+"</option>");

                        uid = data1.beneficiary_id;
                    });
                });
            });


            $('#BeneficiaryCreationForm').submit(function(event){
                event.preventDefault();
                var formdata = new FormData(this);
                if(submission_method == 0){
                    //create new service
                    $.ajax({
                        url: "/beneficiaries/new_Beneficiary/",
                        type: "POST",
                        data: formdata,
                        cache: false,
                        contentType: false,
                        processData: false,
                        success: function(response){
                            alert('New beneficiary is successfully created... :)');
                            submission_method = 0;
                            window.location.reload();
                        },
                        error: function(xhr, status, error){
                            alert('Error while creating beneficiary... :(');
                            submission_method = 0;
                        }
                    });
                }
                else if(submission_method == 1){
                    //update current service
                    $.ajax({
                        url: "/beneficiaries/UpdateBeneficiary/"+ uid,
                        type: "POST",
                        data: formdata,
                        cache: false,
                        contentType: false,
                        processData: false,
                        success: function(response){
                            alert('Beneficiary is successfully updated... :)');
                            submission_method = 0;
                            window.location.reload();
                        },
                        error: function(xhr, status, error){
                            alert('Error while updating beneficiary... :(');
                            submission_method = 0;
                        }
                    });
                }
            });

            $('#form-clear').click(function(event){
                event.preventDefault();
                window.location.reload();

            });

        });
    </script>
    {% endblock %}

PR1/beneficiaries/templates/beneficiaries/beneficiary_id.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/davidshimjs/qrcodejs/qrcode.min.js"></script>
    <script type = "text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.2/jspdf.min.js"></script>
    <script type = "text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.1.4/html2canvas.min.js"></script>
    <link rel="icon" type="image/x-icon" href="{% static 'login/images/sarc-icon.jpg'%}">
    <title>B.R.A.V.e.S</title>
  </head>
  <body>
    <div class = "card" id = "card">
      <button class = 'ribbon'></button>
    <div>
        <img src="{{ben.beneficiary_pic.url}}"  style="width:50%" class = 'ben-pic'>
        <h5  class = 'bid' id = "{{ben.beneficiary_id}}">ID: {{ben.beneficiary_id}}</h5>
        <h3 id = >{{ ben.first_name }} {{ben.middle_name}} {{ben.last_name}}</h3>
        <table class = 'ben-info'>
            <tr>
                <td>Date of Birth:</td>
                <td>{{ben.date_of_birth}}</td>
                <td>Place of Birth:</td>
                <td>{{ben.place_of_birth}}</td>
            </tr>
            <tr>
                <td>Sex:</td>
                <td>{{ben.sex}}</td>
                <td>Household Size:</td>
                <td>{{ben.householod_size}}</td>
            </tr>
            <tr>
                <td>Displacement Status:</td>
                <td>{{ben.displacement_status}}</td>
                <td>Contact:</td>
                <td>{{ben.contact_number}}</td>
            </tr>
        </table>
        <div>
          <div id="qrcode"></div>
        </div>
        <a href="#"><i class="fa fa-dribbble"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-linkedin"></i></a>
        <a href="#"><i class="fa fa-facebook"></i></a>
        <p><button class = 'ribbon'><img src = "{% static 'login/images/sarc-icon.jpg'%}" class = 'sarc-icon'/><small class = 'sarc-contact'>TEL: XXX-XXXXXXX | YYY-YYYYYYY</small></button></p>
      </div>
    </div>
    <div id="editor"></div>
    <div class = 'printID'>
      <button id="printPDF" class = 'btn-active'>Print to PDF</button>
      <a href = "{% url 'beneficiaries_register'%}"><button class = 'btn-clear'>Back to Register</button></a>
    </div>
    </body>
    <style>
        .card {
        border:solid;
        border-width: 1px;
        border-color: rgb(200,0,0);
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        max-width: 250px;
        margin: auto;
        text-align: center;
      }

      .printID{
        max-width: 250px;
        margin: auto;
        text-align: center;
      }

      .ben-pic{
        margin-top: 2%;
      }
      
      .ben-info{
        text-align: left;
        font-size: 8px;
        padding-left: 10px;
      }
      .title {
        color: grey;
        font-size: 9px;
      }

      td{
        padding-right: 10px;
        padding-bottom: 2px;
      }
      
      .ribbon {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: rgb(200,0,0);
        text-align: center;
        cursor: pointer;
        width: 100%;
        font-size: 8px;
      }

      .btn-active{
        margin-top: 20px;
        height: 35px;
        width: 240px;
        background-color: rgba(231, 231, 231, 0);
        color: rgb(200,0,0);
        border: solid 1px rgb(200,0,0);
        border-radius: 4px;
        transition: all 0.1s ease-out;
        font-size: 14 px;
      }
      
      .btn-active:hover{
        background-color: rgb(200,0,0);
        color: white;
        border: solid 1px white;
        transition: all 0.1s ease-out;
      }

      .btn-clear{
        margin-top: 2%;
        height: 35px;
        width: 120px;
        background-color: rgba(231, 231, 231, 0);
        color: rgb(0,0,0);
        border: solid 1px rgb(0,0,0);
        border-radius: 4px;
        transition: all 0.1s ease-out;
      }

      .btn-clear:hover{
        background-color: rgb(0,0,0);
        color: white;
        border: solid 1px white;
        transition: all 0.1s ease-out;
      }

      a {
        margin-top: 5%;
        text-decoration: none;
        font-size: 10px;
        color: black;
      }

    .sarc-contact{
        font-size: 4px;
        text-align: right;
        float: right;
        margin-top: 4%;
    }

    .sarc-icon{
        width: 25px;
        height: 25px;
        border-radius: 50%;
        float: left;
    }

    #qrcode{
      padding-top: 10px;
      margin-left: 80px;
    }
    </style>
    <script>
      $(document).ready(function(){
        var bid = $('.bid').attr('id');
        var qr_content;
        
        $.getJSON('/beneficiaries/GetBeneficiaryByID/' + bid , function(data){
            qr_content = "{"+data.beneficiary_id.toString()+"_"+data.first_name+"_"+data.middle_name+"_"+data.last_name+"_"+data.sex+"_"+"_"+data.place_of_birth+"_"+data.date_of_birth.toString()+"_"+data.contact_number.toString()+"_"+data.current_address+"_"+data.displacement_status+"_"+data.disability_type+"}";

            $("#qrcode").html("");
            var qrcode = new QRCode("qrcode", {
              text: qr_content,
              width: 90,
              height: 90
            }
          ); 
        });

        $('#printPDF').click(function () {
          const div = document.getElementById('card');
 
          html2canvas(div).then(canvas => {
          const imgData = canvas.toDataURL('image/png');

          const doc = new jsPDF();

          doc.addImage(imgData, 'JPEG',  20, 20);
          doc.save(qr_content+'.pdf');
        });
      });
    });
    </script>
</html>