PR1/PR1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings 
from django.conf.urls.static import static 
from login import views as login_views
from admin_ import views as admin_views
from home_ import views as home_views
from services import views as services_views
from beneficiaries import views as beneficiaries_views 
from activities import views as activities_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('home/', include('home_.urls')),
    path('login/', auth_views.LoginView.as_view(template_name = 'login/login.html'), name = 'login'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name = 'login/reset_password.html'), name = 'reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name = 'login/password_reset_sent.html'), name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = 'login/password_reset_form.html'), name = 'password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'login/password_reset_done.html'), name = 'password_reset_complete'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'login/logout.html'), name = 'logout'), 
    path('admin_/', include('admin_.urls')),
    path('activities/', include('activities.urls')),
    path('beneficiaries/', include('beneficiaries.urls')),
    path('services/', include('services.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

PR1/admin/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    role = models.CharField(max_length = 50, choices = [('Admin','Admin'),('Team Leader','Team Leader'),('User','User')], default = 'User')
    
    def __str__(self):
        return f'{self.user.username} Profile'

PR1/admin_/models.py
from django.db import models
from django.contrib.auth.models import User, PermissionsMixin, AbstractBaseUser, BaseUserManager
from PIL import Image

class UserProfileManager(BaseUserManager):
    
    def create_user(self, email, firs_tname, last_name, password):
        if not email:
            raise ValueError('User must have an email address...')

        email = self.normalize_email(email)
        user = self.model(email = email, first_name = firs_tname, last_name = last_name)
        user.set_password(password)
        user.save(using=self._db)

        return user 

    def create_superuser(self, email, first_name, last_name, password):
        user = self.create_user(email,first_name, last_name, password)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)

        return user

class Profile(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    email = models.EmailField(max_length = 255, unique = True, default = 'admin@sarc.org')
    role = models.CharField(max_length = 50, choices = [('Admin','Admin'),('Team Leader','Team Leader'),('User','User')], default = 'User')
    is_active = models.CharField(max_length = 3, choices = [('Yes', 'Yes'),('No','No')], default = 'Yes')
    is_staff = models.BooleanField(default = True)
   
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name','last_name']

    objects = UserProfileManager()

    def __str__(self):
        return f'{self.email}'

PR1/admin_/templates/admin_/change_password.html
{% extends "home_/base.html"%}
{% load crispy_forms_tags%}
{% block content %}
<div class = "actionpage">
    <!--FORM HERE-->
    <form method = 'POST' id = 'ChangePasswordForm'
    style = "
    height: 480px;
    padding-top: 2%;
    width: 45%;
    margin-left: 40%;
    "
    action = "{%url 'change_password' user.email %}">
        {% csrf_token %}
        <fieldset class = 'form-group'>
        <h3 class = 'legend-basic', id = "{{user.email}}">{{user.email}} Change Password</h3> 
            {{form|crispy}}
            <small><a href = "{% url 'UserProfile' user.email %}">Back to profile</a></small>
        </fieldset>
        <div class = 'form-group'>
            <button class = 'btn-active' type = 'submit' style = "width: 150px;">Change Password</button>
        </div>
        <div class = 'messages-container'>
            {% if messages %}
                {% for message in messages %}
                    <p class = "{{message.tags}}">{{message}}</p>
                {% endfor %}
            {% endif %}
          </div>
    </form>

</div>
{% endblock%}

PR1/admin_/templates/admin_/profile.html
{% extends "home_/base.html"%}
{% load crispy_forms_tags%}
{% block content %}
    <div class = "actionpage">
        <!--FORM HERE-->
        <form method = 'POST' enctype = "multipart/form-data", id = 'ProfileUpdateForm', action = "{% url 'UpdateProfile' user.email%}">
            {% csrf_token %}
            <fieldset class = 'form-group'>
                <h3 class = 'legend-basic', id = "{{user.email}}">{{user.email}}</h3>
                {{form|crispy}}
                <small><a href = "{% url 'change_password' user.email %}">Change Password...</a></small>
            </fieldset>
            <div class = 'form-group'>
                <button class = 'btn-active' type = 'submit'>Update</button>
            </div>
        </form>
    </div>
    <div class = 'messages-container'>
        {% if messages %}
            {% for message in messages %}
                <p class = "{{message.tags}}">{{message}}</p>
            {% endfor %}
        {% endif %}
      </div>
    <script>
        $(document).ready(function(){
            var pid = $('.legend-basic').attr('id');
            $.getJSON('/admin_/GetUserByID/' + pid, function(data){
                $('#id_first_name').val(data.first_name);
                $('#id_last_name').val(data.last_name);
            });
            $('#ProfileUpdateForm').submit(function(event){
                
                event.preventDefault();
                $.ajax({
                    url: $(this).attr('action'),
                    type : $(this).attr('method'),
                    data : $(this).serialize(),
                    success: function(response){
                        alert('Profile is updated successfully... :)');
                    },
                    error: function(xhr, status, error){
                        alert('Error while updating profile... :(');
                    }
                });
            });
        });
    </script>
{% endblock %}

PR1/admin_/templates/admin_/register_user.html
{% extends "home_/base.html"%}
{% load crispy_forms_tags%}
{% block content %}
    <div class = "actionpage">
        <div class="action-header">
            <button class = 'btn-active' id = "create-user">Create new user</button>
            <input type = "text" placeholder = "Search"id = 'srch' />
        </div>
        <table>
            <tr id="Grid">
                <th>First Name:</th>
                <th>Last Name:</th>
                <th>Email:</th>
                <th>Active:</th>
                <th>Role:</th>
            </tr>
        </table>
        <div class = 'messages-container'>
            {% if messages %}
                {% for message in messages %}
                    <p class = "{{message.tags}}">{{message}}</p>
                {% endfor %}
            {% endif %}
          </div>
        <div id="myModal" class="modal">
            <div class="modal-content">
                <span class="close">&times;</span>
                <form method = 'POST' id = "UserCreationForm" style = "
                margin-left: 2%;
                margin-top: 1%;
                width: 75%;
                border-radius: 0px;
                box-shadow: none;
                ">
                    {% csrf_token %}
                    <fieldset class = 'form-group'>
                        <legend class = 'legend-basic' id = "users-legend">Create New User</legend>
                        {{form|crispy}}
                        <div class = 'form-group'>
                            <button class = 'btn-active' type = 'submit'>Submit</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function(){

            var submission_method = 0;
            var uid;

            $.getJSON('/admin_/GetAllUsers/', function(data){
                for(var i=0; i < data.length; i++){                
                   $('#Grid').after("<tr class = '"+data[i].is_active+" table-row' id = '"+data[i].email+"''><td>"+data[i].first_name+"</td><td>"+data[i].last_name+"</td><td>"+data[i].email+"</td><td>"+data[i].is_active+"</td><td>"+data[i].role+"</td></tr>");
                }

                $('.table-row').click(function(){
                    $('#myModal').show();
                    submission_method = 1;
                    var row_id = $(this).attr('id');
                    $('#users-legend').text('Edit User');
                    $.getJSON("/admin_/GetUserByID/" + row_id, function(data1){
                        $('#id_first_name').val(data1.first_name);
                        $('#id_last_name').val(data1.last_name);
                        $('#id_email').val(data1.email);
                        $('#id_is_active').prepend("<option value = '"+data1.is_active+"' selected hidden>"+data1.is_active+"</option>");
                        $('#id_role').prepend("<option value = '"+data1.role+"' selected hidden>"+data1.role+"</option>");
                        uid = data1.email;
                    });
                });
            });

            $('#srch').keyup(function(){
                search_table($(this).val());
            });

            function search_table(value){
                $('.table-row').each(function(){
        
                $(this).each(function(){
                    if($(this).text().toLocaleLowerCase().indexOf(value.toLocaleLowerCase()) >= 0){ $(this).show();}
                    else{$(this).hide();}
                    });
                });
            }

            $('#create-user').click(function(){
                $('#myModal').show();
                $('#div_id_password').hide();
            });

            $('.close').click(function(){
                $('#myModal').hide();
                submission_method = 0;
                $('#users-legend').text('Create New User');
                $('#id_first_name').val("");
                $('#id_last_name').val("");
                $('#id_email').val("");
                $('#id_is_active').attr('checked', true);
                $('#id_role').prepend("<option value = 'User' selected hidden>User</option>");
            });

            $('#UserCreationForm').submit(function(event){
                event.preventDefault();
                if(submission_method == 0){
                    //create new user
                    $.ajax({
                        url: "/admin_/new_user/",
                        type: "POST",
                        data: $(this).serialize(),
                        success: function(response){
                            alert('New user is successfully created... :)');
                            submission_method = 0;
                            window.location.reload();
                        },
                        error: function(xhr, status, error){
                            alert('Error while creating user... :(');
                            submission_method = 0;
                        }
                    });
                }
                else if(submission_method == 1){
                    //update current user
                    $.ajax({
                        url: "/admin_/UpdateUser/"+ uid,
                        type: "POST",
                        data: $(this).serialize(),
                        success: function(response){
                            alert('User is successfully updated... :)');
                            submission_method = 0;
                            window.location.reload();
                        },
                        error: function(xhr, status, error){
                            alert('Error while updating user... :(');
                            submission_method = 0;
                        }
                    });
                }
            });
        });
    </script>
    {% endblock %}